### ISSUE TITLE
JFP revisions tracking bug

### ISSUE THREAD

**Issue by lkuper** [lkuper/dissertation#8]
Reviewer 1 made three major requests:

>  1. Serious thought given to the suggestion of merging lambda_LVar and
>     lambda_LVish into just one calculus, so as to reduce duplication and
>     shorten the paper. The new calculus should be as simple as lambda_LVar and
>     as powerful as lambda_LVish. Is it possible? I would like to think so, but
>     perhaps I am being naive.

>  2. An explicit presentation of the LVish API, possibly at the cost of
>     consuming extra space;

>  3. A fuller presentation and a better explanation of the LVish implementation.

We're doing the first two (see issues #3 and #6), but skipping 3, for reasons I discuss more in [my notes here](https://github.com/lkuper/dissertation/blob/master/dissertation/jfp-reviews-notes.md).

Reviewer 2 had five major suggestions, which I'll try to summarize as follows:

  1. *Lubs and lattices are a red herring; this should be about posets* -- We're acknowledging this by taking some of the focus off of lubs, but to follow all their suggestions would be to change the flavor and focus of the work pretty drastically; we should push back.
  2. *Resolve the question about consistent termination* -- Yes, we should.  Issue #7.
  3. *Add an account of how we deal with early termination and parallel or* -- Yes, we should.  Issue #4.
  4. *Tone down the claim that we subsume KPNs* -- Yes, we should (and reviewer 1 commented on this as well).  Issue #5.
  5. I'm still thinking about how to summarize and respond to point 5.

So, here's our checklist:
  - [ ] Move arbitrary updates over to lambdaLVar (issue #3) (@lkuper)
  - [ ] Systematic presentation of LVish API (issue #6) (@rrnewton)
  - [ ] Resolve question about consistent termination (issue #7) (???)
  - [ ] Add stuff about early termination and parallel or (issue #4) (@lkuper)
  - [ ] Tone down the claim that we subsume KPNs (issue #5) (@rrnewton)
  - [ ] Reviewer 2 point 5...

**Comment by rrnewton** [comment]
How about all the small copy edits that were listed in the reviews.  Are those done already?

**Comment by lkuper** [comment]
All of the copy edits from review 1 are done.  I'll go over review 2 too.
